# use prebuild packages on ubuntu
if (tolower(Sys.info()[["sysname"]]) == "linux") {
  options(repos = c(CRAN = "https://packagemanager.posit.co/cran/__linux__/noble/latest"))
}


# install necessary packages
install.packages(c("devtools"))
devtools::install_github("etiennebacher/altdoc")

dir.create(file.path(getwd(), "R"))
dir.create(file.path(getwd(), "man"))
pkg_name <- "issue" 

# Create DESCRIPTION file
description_content <- sprintf(
  "Package: %s\nType: Package\nTitle: What the Package Does (One Line, Title Case)\nVersion: 0.1.0\nAuthor: Your Name\nMaintainer: Your Name <your@email.com>\nDescription: A short description of the package.\nLicense: MIT\nEncoding: UTF-8\nLazyData: true\nRoxygenNote: 7.2.3\n",
  pkg_name
)
writeLines(description_content, file.path(getwd(), "DESCRIPTION"))

# Create NAMESPACE file
namespace_content <- "# Generated by roxygen2: do not edit by hand"
writeLines(namespace_content, file.path(getwd(), "NAMESPACE"))

# Define the function with roxygen2 comments
func_code <- c(
  "#' A title",
  "#'",
  "#' @param x a number.",
  "#' @return x.",
  "#' @export",
  "squareNumber <- function(x) {",
  " x^2",
  "}"
)

# Write the function to the R/ folder
writeLines(func_code, file.path(getwd(), "R", paste0("test", ".R")))

# Generate documentation
devtools::document()

# Setup and build documentation using altdoc
altdoc::setup_docs(tool = "docsify")
altdoc::render_docs()

cat("Package created and documented at:", pkg_name, "\n")
